### ISSUE TITLE
Authentication is not working

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/client-python#11]
I know that the code is generated but it seems like kubernetes and openshift are doing it in correct way.

Auth settings in [configuration.py](https://github.com/kubevirt/client-python/blob/master/kubevirt/configuration.py#L203) is missing. Here is working [auth_setting](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py#L222).

It is not enough we need to update each api call with `auth_settings = ['BearerToken']` in similar way as it is done in openshift in many places but [here](https://github.com/openshift/openshift-restclient-python/blob/4a6bb1fac658557fe724b626bf7115517d83b023/openshift/client/apis/authorization_openshift_io_v1_api.py#L121) is an example.

Please make sure that generated code works properly.

**Comment by pkliczewski** [comment]
@lukas-bednar it is critical item for virt-who work.

**Comment by lukas-bednar** [comment]
I did some small research and in order to do allow this auth methods, the openapispec needs to define `securityDefinitions`. I will add this section.
