### ISSUE TITLE
Listing vms for all namespaces returns vmpresets

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/client-python#12]
When I call `list_virtual_machine_for_all_namespaces` I get `VirtualMachinePresetList` instead of list of `VirtualMachineList`. [This](https://github.com/kubevirt/client-python/blob/master/kubevirt/apis/default_api.py#L2965) url is wrong.

**Comment by pkliczewski** [comment]
@lukas-bednar fyi

**Comment by pkliczewski** [comment]
`list_virtual_machine_for_all_namespaces_0` seems to work fine

**Comment by lukas-bednar** [comment]
#9

**Comment by pkliczewski** [comment]
Since it is a duplicate no need to have it open.
