### ISSUE TITLE
Use examples to be mini test suite

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/client-python#15]
This mini test suite should be passed before pushing new version into repository.

**Comment by lukas-bednar** [comment]
Where to test it ?
We can integrate with STD-CI to deploy cluster and run these examples / mini-suite.
Or we can test it in kubevirt repository before pushing into client repo.

**Comment by lukas-bednar** [comment]
Based on discussion at community meeting, the preferred way is test it on kubevirt side!

**Comment by pkliczewski** [comment]
I disagree that testing it on Kubevirt side is good approach.

**Comment by pkliczewski** [comment]
Not needed anymore.
