### ISSUE TITLE
Generate a map for KubeVirt's resources and their actions

### ISSUE THREAD

**Issue by tripledes** [kubevirt/client-python#19]
It'd be quite helpful to have a map for KubeVirt's resources and the actions that can be performed on them so the users of the Python client can be abstracted of the object's specifics.

**Comment by lukas-bednar** [comment]
This will have to be generated on kubevirt side. Do you have any suggestion how such map should look like ?

**Comment by tripledes** [comment]
Without going too much into details, my idea would to have a method that given the resource type (OVM, VMRS, VMPresets, ....) and API version, would return and object with it's methods with generic names like create, patch, replace...and even the correct model given the API version (V?VirtualMachinePreset, ....).

That would be my ideal abstraction, not sure how that would fit in the current implementation though.

Thanks!

**Comment by pkliczewski** [comment]
Maybe we can follow the same [approach](https://www.ansible.com/blog/dynamic-kubernetes-client-for-ansible) as Kubernetes.

**Comment by pkliczewski** [comment]
This issue is no needed anymore.
