### ISSUE TITLE
Find a way how to load kubeconfig transparently

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/client-python#2]
When working with [kubernetes-pysdk](https://github.com/kubernetes-incubator/client-python) they provide function which loads kubeconfig, and configure client.
```python
from kubernetes import config
config.load_kube_config(PATH_TO_KUBECONFIG)
```
Generated SDK doesn't have such function.
It can be workarounded by following snippet
```python
from kubernetes import config
import kubevirt
cl = config.kube_config._get_kube_config_loader_for_yaml_file(PATH_TO_KUBECONFIG)
cl.load_and_set(kubevirt.configuration)
```
It would be handy to add such function to client.
As a side effect it brings kubernetes-pysdk as dependency.
On other hand user will probably work with both, kubernetes &  kubevirt - so it is not really problem.

**Comment by pkliczewski** [comment]
We use k8s dynamic client now so not needed.
