### ISSUE TITLE
No tag for significant api changes

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/client-python#22]
Recently we bumped api version due to renaming of `ovm` to `vm` and `vm' to `vmi`. Please provide a way to from which commit we can use newer version.

**Comment by pkliczewski** [comment]
@lukas-bednar cc

**Comment by lukas-bednar** [comment]
I don't know how to deal with this properly. This code is auto-generated after every merge of PRs which committed changes into KubeVirt's OpenAPI specification. I guess we can push tag to this repository per each KubeVirt release, with same name ...

@rmohr  do you have any suggestion ? I remember that we were discussing this in the past, but didn't come with conclusion.

**Comment by lukas-bednar** [comment]
Based on discussion at community meeting, we push tag on every kubevirt release.
In addition we will create branches for release-0.4 & release-0.6 .

**Comment by pkliczewski** [comment]
We need to synchronize api changes with kubevirt so we can version the client.

**Comment by rmohr** [comment]
> We need to synchronize api changes with kubevirt so we can version the client.

@pkliczewski yes, not sure if my comment is helpful but whenever kubevirt is released the kubevirt release-job can also do the tagging on the client-python repo. Should be pretty easy since we already push content to this repo on every build in kubevirt: https://github.com/kubevirt/kubevirt/blob/master/hack/gen-client-python/deploy.sh.

**Comment by pkliczewski** [comment]
@rmohr This should be good to start with. I noticed that sometimes when we update our dependencies like generators or k8s there are changes in api definition which we need to handle somehow. I have one additional remark that we do not need to update client's version if there were no changes on the api level.

I am thinking on using [dynamic client](https://github.com/openshift/openshift-restclient-python/#openshift-python-client) which would remove a need to version anything.

**Comment by pkliczewski** [comment]
No need for this issue anymore.
