### ISSUE TITLE
kubevirt-py package version does not conform to PEP 440

### ISSUE THREAD

**Issue by bhuwan87** [kubevirt/client-python#56]
Current kubevirt-py package version is v1.1.0-rc.0-283-g59b933853. It is non-conformant to PEP 440.  It throws invalid version error while doing pip install kubevirt-py package.

#15 4.769 Defaulting to user installation because normal site-packages is not writeable
#15 4.835 Collecting git+https://github.com/kubevirt/client-python.git (from -r requirements.txt (line 7))
#15 4.837   Cloning https://github.com/kubevirt/client-python.git to /tmp/pip-req-build-tqun88di
#15 4.843   Running command git clone --filter=blob:none --quiet https://github.com/kubevirt/client-python.git /tmp/pip-req-build-tqun88di
#15 10.04   Resolved https://github.com/kubevirt/client-python.git to commit 7739604fd2d46e62effbd6b5007e889618da189c
#15 10.05   Installing build dependencies: started
#15 13.48   Installing build dependencies: finished with status 'done'
#15 13.48   Getting requirements to build wheel: started
#15 13.67   Getting requirements to build wheel: finished with status 'error'
#15 13.68   error: subprocess-exited-with-error
#15 13.68   
#15 13.68   × Getting requirements to build wheel did not run successfully.
#15 13.68   │ exit code: 1
#15 13.68   ╰─> [27 lines of output]
#15 13.68       Traceback (most recent call last):
#15 13.68         File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#15 13.68           main()
#15 13.68         File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#15 13.68           json_out['return_val'] = hook(**hook_input['kwargs'])
#15 13.68         File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#15 13.68           return hook(config_settings)
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
#15 13.68           return self._get_build_requires(config_settings, requirements=['wheel'])
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
#15 13.68           self.run_setup()
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
#15 13.68           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
#15 13.68           exec(code, locals())
#15 13.68         File "<string>", line 28, in <module>
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
#15 13.68           return distutils.core.setup(**attrs)
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
#15 13.68           _setup_distribution = dist = klass(attrs)
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 314, in __init__
#15 13.68           self.metadata.version = self._normalize_version(self.metadata.version)
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 350, in _normalize_version
#15 13.68           normalized = str(Version(version))
#15 13.68         File "/tmp/pip-build-env-_umdstd6/overlay/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
#15 13.68           raise InvalidVersion(f"Invalid version: '{version}'")
#15 13.68       setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'v1.1.0-rc.0-283-g59b933853'
#15 13.68       [end of output]
#15 13.68   
#15 13.68   note: This error originates from a subprocess, and is likely not a problem with pip.
#15 13.69 error: subprocess-exited-with-error
#15 13.69 
#15 13.69 × Getting requirements to build wheel did not run successfully.
#15 13.69 │ exit code: 1
#15 13.69 ╰─> See above for output.
#15 13.69 
#15 13.69 note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by umangutkarsh** [comment]
Any response?

**Comment by GoshaDo** [comment]
Same for me, 
`Invalid version 'v1.2.0-rc.0-409-ga8f47af81' on package kubevirt-py`

**Comment by sproutmaster** [comment]
I get the error too `setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'v1.3.0-beta.0-202-gf8efa5771'`
